name: CI/CD
on:
  pull_request:
    branches: [main, master, dev]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        # No version specified - uses packageManager from package.json
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Run linting
        run: pnpm run lint --filter=\!@workspace/ui
        
      - name: Check formatting
        run: pnpm run format:check --filter=\!@workspace/ui
        
      - name: Build Web project
        run: cd apps/web && pnpm run typecheck
        
      - name: Generate Prisma Client
        run: cd packages/db && pnpm run db:generate
        
      - name: Build Server project
        run: cd apps/server && pnpm run typecheck
