name: CI/CD

on:
  pull_request:
    branches: [main, master, dev]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8  # or 9 if you're using pnpm 9
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install  # Changed from 'pnpm ci'
        
      - name: Run linting
        run: pnpm run lint
        
      - name: Check formatting
        run: pnpm run format:check
        
      - name: Build Web project
        run: cd apps/web && pnpm run typecheck
        
      - name: Generate Prisma Client
        run: cd packages/db && pnpm run db:generate
        
      - name: Build Server project
        run: cd apps/server && pnpm run typecheck
